app:
  name: rsvp-db
  namespace: sskd
  replicas: 1
  port: 5432

  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent

  imagePullSecrets: []

  env:
    POSTGRES_DB: rsvp_db
    POSTGRES_USER:
      valueFrom:
        secretKeyRef:
          name: rsvp-db-secrets
          key: PGUSER
    POSTGRES_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: rsvp-db-secrets
          key: PGPASSWORD

  livenessProbe: null
  readinessProbe: null

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
    mountPath: /var/lib/postgresql/data

  ingress:
    enabled: false
